# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: dask-cudf
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ../../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

# FIXME: cudf 0.7 post build _652 is required in order to properly
# ensure rmm is also present. This additional restriction should be
# removed when the cudf dependency is upgraded for 0.8

requirements:
  build:
    - python x.x
    - cudf 0.7*,>*py36_652
    - dask >=0.19.0
    - distributed >=1.23.0
  run:
    - python x.x
    - cudf 0.7*,>*py36_652
    - dask >=0.19.0
    - distributed >=1.23.0
test:
  imports:
    - dask_cudf

about:
  home: http://rapids.ai
  license: Apache
  license_file: ../../../LICENSE.txt
  summary: dask-cudf library
